FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./

RUN npm install || true

COPY . .

RUN npx prisma generate

EXPOSE 4000

CMD ["npm", "run", "dev"]